### ISSUE TITLE
make GeoUtils.convertLongitudeRangeto180 more generic

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-search#118]
[convertLongitudeRangeTo180](https://github.com/ESGF/esg-search/blob/74217e98e9669c3db843e607b863c1306c34ac15/src/java/main/esg/search/utils/GeoUtils.java) makes assumptions about longitude ranges which are not valid in some real datasets.  An example is `cmip5.output1.BCC.bcc-csm1-1.historical.mon.ocean.Omon.r2i1p1.v20130329`, which has longitude range -279.5 to 79.5 -- see the  [THREDDS catalog](https://aims3.llnl.gov/thredds/catalog/esgcet/170/cmip5.output1.BCC.bcc-csm1-1.historical.mon.ocean.Omon.r2i1p1.v20130329.xml), which contains:
```
<eastwest>
    <start>-279.5</start>
    <size>359.0</size>
    <units>degrees_east</units>
</eastwest>
```
Such datasets were previously published to indexes (without any `geo` tag), but cannot be republished to Solr using the current version of the publication service. This is because it does not convert the longitude range properly, and this leads to the Solr exception:
```
org.apache.solr.common.SolrException; org.apache.solr.common.SolrException: Couldn't parse shape 'ENVELOPE(-279.5, 79.5, 89.5, -81.5)' because: Bad X value -279.5 is not in boundary Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)
```
resulting in:
`Server returned HTTP response code: 400 for URL: http://localhost:8984/solr/datasets/update`

The following tested example code has logic which deals correctly with any longitude range subject only to the condition that `0 <= (lonMax - lonMin) < 360`, but because I do not program in Java it is written in Python.  Hopefully it should be an easy job to write a Java version that uses this same logic.

```
def convertLongitudeRangeTo180(lonMin, lonMax):

    assert(lonMax >= lonMin and 
           lonMax < lonMin + 360)

    ranges = []

    while lonMin < -180.:
        lonMin += 360.
        lonMax += 360.

    while lonMin >= 180.:
        lonMin -= 360.
        lonMax -= 360.

    if lonMax >= 180.:
        ranges.append([-180., lonMax - 360.])
        ranges.append([lonMin, 180.])

    else:
        ranges.append([lonMin, lonMax])

    return ranges
```

In the -279.5 to 79.5 case, it gives: ranges `[-180., 79.5]` and `[80.5, 180.]`

**Comment by LucaCinquini** [comment]
I converted your code to Java, please take a look. Thanks for the fix.

**Comment by alaniwi** [comment]
Your test for invalid values permits `lonMax == lonMin + 360`. I am not sure whether it should permit that, because then the same location appears at both ends of the range. I would suggest perhaps changing the `>` to `>=` in line 18. (This would be equivalent to my `assert`.) But if it is to be permitted, then I think we would need to change the `>=` to `>` in line 34. It also depends whether a value of exactly +180 is acceptable to Solr, which I don't know. What do you reckon?

**Comment by alaniwi** [comment]
Also there is a bug in line 24. It should say `-180` (note sign), as per the above Python code.

**Comment by LucaCinquini** [comment]
Sorry Alan, I should have been more careful. I made the Java code just like the Python code, thanks again, L

**Comment by alaniwi** [comment]
Thanks.
