### ISSUE TITLE
project-specific search fails immediately after esg-node restart

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-search#126]
If you set up CoG projects with associated search that has a "project" constraint, any search on this page will fail after a node restart until the first search without the project constraint has been performed.

Example:

* After a node restart, going to https://esgf-index1.ceda.ac.uk/search/cmip5-ceda/ gives "Error: search may not be properly configured. Contact the Project Administrator."

* The log shows that it is attempting a search at https://esgf-index1.ceda.ac.uk/esg-search/search/?offset=0&limit=0&type=Dataset&replica=false&latest=true&project=CMIP5&project=TAMIP&project=EUCLIPSE&project=LUCID&project=GeoMIP&project=PMIP3&facets=project%2Cproduct%2Cinstitute%2Cmodel%2Cexperiment%2Cexperiment_family%2Ctime_frequency%2Crealm%2Ccmor_table%2Censemble%2Cvariable%2Cvariable_long_name%2Ccf_standard_name%2Cdata_node

* Attempting this search directly in the client, a 400 error from Tomcat is seen with message: "Invalid HTTP query parameter=project"

* This happens repeatably, on any of the similar project-specific search pages.

* A non-project-specific search is then performed, for example via the default CoG project or a direct client GET of a similar esg-search URL but without the `project=...` parameters.  It does not have to be from the same client IP.

* Project-specific searches then start working.

**Comment by alaniwi** [comment]
It seems that the error is not specific to the `project` parameter. A similar search with `mip_era` constraint has the same problem after a restart.

And another example of a URL which will clear the problem is the top-level `http://<hostname>/esg-search/search/`

**Comment by LucaCinquini** [comment]
Hi Alan, I cannot reproduce this. I defined a CoG project with search constraint project=obs4MIps, restarted the node, hit the CoG search page, and it works. Is it possible you were woking with an empty Solr index ?

The message you saw is thrown by the search when the facet is not recognized. This can happen if no data has ever been published that has that facet.

Maybe we could go on a conference call next Wednesday before the Data Challenge call, and try things together while sharing screen ?

thanks, Luca

**Comment by sashakames** [comment]
Assuming this issue was based on what Luca suggested was the problem, its a non-issue.
