### ISSUE TITLE
sha256sum command is missing in MacOSX

### ISSUE THREAD

**Issue by cofinoa** [ESGF/esg-search#84]
The sha256sum command used in wget script, for sha25 checksum, is missing on default MacOSX installations.

**Comment by cofinoa** [comment]
Possible solutions (just use one of these):

1. Install GNU coreutils package provided by MacPorts. Other package managers, like Fink, would work. 
2. If no package manager is intalled then another possible solution: `function sha256sum() { openssl sha256 "$@" | awk '{print $2}'; }`
3. Or use shasum perl script, creating an alias (installed by default in lateste MacOSX releases >Leopard: `alias sha256sum="shasum -a 256"`

The last 2 solutions should be added to user's .bashrc file.

**Comment by cofinoa** [comment]
The wget template should include a own sha256sum_ function like md5sum

**Comment by cofinoa** [comment]
Bash aliases are not exported to invoked scripts. But shell/bash functions, like variables, can be exported. Therefore create a function and then export it:
`function sha256sum() { shasum -a 256 "$@" ; } && export -f sha256sum`
add to your  `$HOME/.bashrc` file

**Comment by TorstenRathmann** [comment]
Solutions 1 and 2 are added to Wget FAQ, https://www.earthsystemcog.org/projects/cog/doc/esgf/faq/wget
Solution 3 will be included in Wget scripts itself as Katharina told me.

**Comment by rjoffray** [comment]
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

solved!
